version: '3.1'
services:
  odoo16:
    container_name: ${ODOO_DEVELOPER}_odoo
    image: odoo
    networks:
      - odoo-network
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_DEBUG_PORT}:3001"
    environment:
      - DB_PORT_5432_TCP_ADDR=${DB_PORT_5432_TCP_ADDR}
      - DB_PORT_5432_TCP_PORT=${DB_PORT_5432_TCP_PORT}
      - DB_ENV_POSTGRES_USER=${DB_ENV_POSTGRES_USER}
      - DB_ENV_POSTGRES_PASSWORD=${DB_ENV_POSTGRES_PASSWORD}
      - ODOO_DEBUG_PORT=${ODOO_DEBUG_PORT}
      - ODOO_AUTO_UPDATE_MODULES=${ODOO_AUTO_UPDATE_MODULES}
      - ODOO_MODULES=${ODOO_MODULES}
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./conf/:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./log:/var/log/odoo
volumes:
  odoo_web_data:
networks:
  odoo-network: